export interface Challenge {
    id: string;
    text: string;
    category: 'SOCIAL' | 'ABSURD' | 'RISKY';
}

export const CHALLENGES: Challenge[] = [
    // === SOCIAL (100) - Décalages de comportement et petites gênes ===
    { id: 'S1', text: "Faire un compliment très spécifique sur la symétrie du visage de quelqu'un.", category: 'SOCIAL' },
    { id: 'S2', text: "Se toucher l'oreille gauche 3 fois dès que vous prenez la parole.", category: 'SOCIAL' },
    { id: 'S3', text: "Bailler bruyamment, puis s'arrêter net en fixant quelqu'un.", category: 'SOCIAL' },
    { id: 'S4', text: "Répéter la dernière phrase de votre interlocuteur sous forme de question.", category: 'SOCIAL' },
    { id: 'S5', text: "Siffler un air très connu mais très doucement pendant un silence.", category: 'SOCIAL' },
    { id: 'S6', text: "Changer de place avec quelqu'un sans donner de raison valable.", category: 'SOCIAL' },
    { id: 'S7', text: "Applaudir très brièvement après qu'une personne ait fini de boire.", category: 'SOCIAL' },
    { id: 'S8', text: "Demander à quelqu'un s'il n'a pas l'impression que la pièce penche vers la gauche.", category: 'SOCIAL' },
    { id: 'S9', text: "Faire un clin d'œil appuyé après avoir dit une phrase banale comme 'Il fait beau'.", category: 'SOCIAL' },
    { id: 'S10', text: "Parler de votre passion pour les élevages de phasmes pendant 1 minute.", category: 'SOCIAL' },
    { id: 'S11', text: "Demander à quelqu'un de vous tenir votre verre 'juste deux secondes' sans bouger.", category: 'SOCIAL' },
    { id: 'S12', text: "Rire de bon cœur à une phrase qui n'était absolument pas une blague.", category: 'SOCIAL' },
    { id: 'S13', text: "Proposer un toast : 'À la santé des girafes et de leur long cou'.", category: 'SOCIAL' },
    { id: 'S14', text: "Demander à quelqu'un s'il n'a pas un 'nuage de charisme' au-dessus de la tête.", category: 'SOCIAL' },
    { id: 'S15', text: "S'excuser platement auprès d'une fourchette après l'avoir fait tomber.", category: 'SOCIAL' },
    { id: 'S16', text: "Demander le prénom d'une personne que vous connaissez depuis des années.", category: 'SOCIAL' },
    { id: 'S17', text: "Redire 'Enchanté' à la même personne pour la troisième fois du repas.", category: 'SOCIAL' },
    { id: 'S18', text: "Demander conseil sur la manière 'la plus élégante' de poser ses mains sur la table.", category: 'SOCIAL' },
    { id: 'S19', text: "Féliciter quelqu'un avec beaucoup de sérieux après qu'il ait utilisé un mot de plus de trois syllabes.", category: 'SOCIAL' },
    { id: 'S20', text: "Regarder fixement le front de la personne qui vous parle.", category: 'SOCIAL' },
    { id: 'S21', text: "Appeler quelqu'un par le nom d'un personnage de film pendant 2 minutes.", category: 'SOCIAL' },
    { id: 'S22', text: "Proposer de lire l'avenir dans les lignes de la main avec beaucoup de sérieux.", category: 'SOCIAL' },
    { id: 'S23', text: "Dire 'C'est fou ça...' après chaque phrase de votre voisin.", category: 'SOCIAL' },
    { id: 'S24', text: "Demander à voix basse : 'Est-ce que vous aussi vous sentez cette odeur de pop-corn ?'.", category: 'SOCIAL' },
    { id: 'S25', text: "Avoir un hoquet très sonore, une seule fois, de façon très théâtrale.", category: 'SOCIAL' },
    { id: 'S26', text: "Essayer de parler sans jamais utiliser de mots contenant la lettre 'R'.", category: 'SOCIAL' },
    { id: 'S27', text: "Demander l'avis du groupe sur : 'Quelle est la meilleure forme de pâtes ?'.", category: 'SOCIAL' },
    { id: 'S28', text: "Prétendre que vous avez un oncle qui a inventé le bouton de chemise.", category: 'SOCIAL' },
    { id: 'S29', text: "Dire 'Chut !' en regardant le plafond, puis reprendre la discussion.", category: 'SOCIAL' },
    { id: 'S30', text: "Prendre un accent très léger et indéfinissable pendant trois phrases.", category: 'SOCIAL' },
    { id: 'S31', text: "Demander si quelqu'un a une solution contre les 'fourmis dans les sourcils'.", category: 'SOCIAL' },
    { id: 'S32', text: "Initier un check complexe qui finit en Pierre-Feuille-Ciseaux.", category: 'SOCIAL' },
    { id: 'S33', text: "Raconter une anecdote sur une pomme de terre qui n'a pas de fin.", category: 'SOCIAL' },
    { id: 'S34', text: "Dire 'Tu n'aurais pas dû dire ça...' avec un regard mystérieux.", category: 'SOCIAL' },
    { id: 'S35', text: "Faire épeler son propre prénom à quelqu'un, très lentement.", category: 'SOCIAL' },
    { id: 'S36', text: "Remplacer le mot 'Chaise' par 'Le support de gravité personnel'.", category: 'SOCIAL' },
    { id: 'S37', text: "S'exclamer 'La prophétie !' apès une action d'un autre joueur.", category: 'SOCIAL' },
    { id: 'S38', text: "Demander très sérieusement : 'Tu penses que les poissons ont soif ?'.", category: 'SOCIAL' },
    { id: 'S39', text: "Sautiller une fois sur place avant de vous rasseoir.", category: 'SOCIAL' },
    { id: 'S40', text: "Dire 'Exactement !' en pointant du doigt quelqu'un qui n'a rien dit.", category: 'SOCIAL' },
    { id: 'S41', text: "Lancer un concours de celui qui cligne des yeux en dernier.", category: 'SOCIAL' },
    { id: 'S42', text: "Prétendre que vous entendez un sifflement que personne d'autre n'entend.", category: 'SOCIAL' },
    { id: 'S43', text: "Demander à votre voisin s'il peut vous aider à 'ranger votre aura'.", category: 'SOCIAL' },
    { id: 'S44', text: "Débattre avec ferveur : 'Faut-il mettre les céréales avant ou après le lait ?'.", category: 'SOCIAL' },
    { id: 'S45', text: "Dire que vous avez une peur panique des genoux (la génuphobie).", category: 'SOCIAL' },
    { id: 'S46', text: "Comparer le rire de quelqu'un au chant d'un oiseau rare (en compliment).", category: 'SOCIAL' },
    { id: 'S47', text: "Simuler une conversation téléphonique très courte avec votre main (sans téléphone).", category: 'SOCIAL' },
    { id: 'S48', text: "Chercher un objet imaginaire sur la table pendant 30 secondes.", category: 'SOCIAL' },
    { id: 'S49', text: "Dire 'Bingo !la prochaine fois que quelqu'un dit le mot 'Oui'.", category: 'SOCIAL' },
    { id: 'S50', text: "Proposer de renommer les jours de la semaine par des noms de navigateurs célèbres.", category: 'SOCIAL' },
    { id: 'S51', text: "Se frotter les mains énergiquement avant de toucher vos couverts.", category: 'SOCIAL' },
    { id: 'S52', text: "Demander : 'Est-ce que vous trouvez que les tables sont trop horizontales ?'.", category: 'SOCIAL' },
    { id: 'S53', text: "Affirmer que vous parlez couramment le langage des yeux.", category: 'SOCIAL' },
    { id: 'S54', text: "Répondre 'C'est pas faux' à tout ce qu'on vous dit pendant 2 minutes.", category: 'SOCIAL' },
    { id: 'S55', text: "Prétendre que vous avez un flash du futur concernant le dessert.", category: 'SOCIAL' },
    { id: 'S56', text: "Demander à quelqu'un s'il veut votre autographe sur sa serviette.", category: 'SOCIAL' },
    { id: 'S57', text: "Dire 'Oups, mon autre moi prend le dessus' après un éternuement.", category: 'SOCIAL' },
    { id: 'S58', text: "Essayer de faire une tour avec les morceaux de pain sur la table.", category: 'SOCIAL' },
    { id: 'S59', text: "Demander si vous pouvez 'emprunter une émotion' à quelqu'un.", category: 'SOCIAL' },
    { id: 'S60', text: "Dire 'C'est noté' d'un air très sérieux après une phrase banale.", category: 'SOCIAL' },
    { id: 'S61', text: "S'asseoir sur le bord extrême de sa chaise comme si on allait s'envoler.", category: 'SOCIAL' },
    { id: 'S62', text: "Demander à la ronde : 'Qui croit aux chats télépathes ?'.", category: 'SOCIAL' },
    { id: 'S63', text: "Faire semblant d'avoir un troisième bras invisible pour porter votre verre.", category: 'SOCIAL' },
    { id: 'S64', text: "Dire 'Visez la lune !' au milieu d'un silence total.", category: 'SOCIAL' },
    { id: 'S65', text: "Proposer de créer un fan-club pour le sel de table.", category: 'SOCIAL' },
    { id: 'S66', text: "Demander : 'Tu as payé ta taxe sur l'humour aujourd'hui ?'.", category: 'SOCIAL' },
    { id: 'S67', text: "Dire 'Maudit soit ce jambon' sans raison particulière.", category: 'SOCIAL' },
    { id: 'S68', text: "Taper un rythme sur la table et dire : 'C'est du Morse pour : j'ai faim'.", category: 'SOCIAL' },
    { id: 'S69', text: "Demander à quelqu'un de surveiller votre ombre deux minutes.", category: 'SOCIAL' },
    { id: 'S70', text: "Deviner le signe astrologique de tout le monde (et se tromper volontairement).", category: 'SOCIAL' },
    { id: 'S71', text: "Faire semblant d'être allergique au mot 'Précisément'.", category: 'SOCIAL' },
    { id: 'S72', text: "S'émerveiller devant la réfraction de la lumière dans votre verre.", category: 'SOCIAL' },
    { id: 'S73', text: "Dire 'Il était temps qu'on en vienne au fait' après qu'on vous ait demandé le sel.", category: 'SOCIAL' },
    { id: 'S74', text: "Lancer une Ola tout seul, avec enthousiasme.", category: 'SOCIAL' },
    { id: 'S75', text: "Demander : 'Tu penses qu'on peut faire du ski sur de la purée ?'.", category: 'SOCIAL' },
    { id: 'S76', text: "Crier 'Alerte rouge !' si une goutte d'eau tombe sur la nappe.", category: 'SOCIAL' },
    { id: 'S77', text: "Prétendre que vous collectionnez les enregistrements de bruits de klaxons.", category: 'SOCIAL' },
    { id: 'S78', text: "Demander à quelqu'un s'il a le numéro de téléphone du Père Noël.", category: 'SOCIAL' },
    { id: 'S79', text: "Dire 'Je savais que tu dirais ça' à chaque fois que quelqu'un parle.", category: 'SOCIAL' },
    { id: 'S80', text: "Faire un solo de 'Air Piano' sur le bord de la table.", category: 'SOCIAL' },
    { id: 'S81', text: "Demander : 'Est-ce que vous voyez aussi ce petit reflet sur l'épaule de Paul ?'.", category: 'SOCIAL' },
    { id: 'S82', text: "Finir vos phrases par '... et c'est mon dernier mot !'.", category: 'SOCIAL' },
    { id: 'S83', text: "Confier un faux secret : 'Je ne sais pas nager avec des chaussettes'.", category: 'SOCIAL' },
    { id: 'S84', text: "Demander quelle est la différence entre un canard (ne pas finir la phrase).", category: 'SOCIAL' },
    { id: 'S85', text: "S'exclamer 'Eurêka !' et pointer une miette de pain.", category: 'SOCIAL' },
    { id: 'S86', text: "Proposer de renommer le lundi 'Le Grand Sommeil'.", category: 'SOCIAL' },
    { id: 'S87', text: "Demander : 'Quelqu'un a vu mon enthousiasme ? Je l'ai posé là'.", category: 'SOCIAL' },
    { id: 'S88', text: "Dire 'C'est lunaire !' dès que quelqu'un sourit.", category: 'SOCIAL' },
    { id: 'S89', text: "Prétendre que vous avez un talent pour deviner le prix des objets au toucher.", category: 'SOCIAL' },
    { id: 'S90', text: "Vérifier si les coudes de votre voisin sont 'parallèles au sol'.", category: 'SOCIAL' },
    { id: 'S91', text: "Dire 'Mince alors' dès que quelqu'un pose un couvert sur la table.", category: 'SOCIAL' },
    { id: 'S92', text: "Demander une minute de silence pour la fin du plat principal.", category: 'SOCIAL' },
    { id: 'S93', text: "Demander si quelqu'un a déjà vu un pigeon faire du breakdance.", category: 'SOCIAL' },
    { id: 'S94', text: "Affirmer que les cafetières complotent contre le thé.", category: 'SOCIAL' },
    { id: 'S95', text: "Prétendre que vous savez lire dans les pensées des olives.", category: 'SOCIAL' },
    { id: 'S96', text: "Demander : 'C'est quoi votre plan B si la gravité s'arrête ?'.", category: 'SOCIAL' },
    { id: 'S97', text: "Dire 'Attention, le chef arrive !' et se tenir très droit.", category: 'SOCIAL' },
    { id: 'S98', text: "Organiser un vote pour élire la 'meilleure fourchette du lot'.", category: 'SOCIAL' },
    { id: 'S99', text: "Demander : 'Tu préférerais avoir des mains à la place des pieds ou l'inverse ?'.", category: 'SOCIAL' },
    { id: 'S100', text: "Dire 'Et voilà le travail !' après avoir simplement respiré fort.", category: 'SOCIAL' },

    // === ABSURD (100) - Délires technologiques et gestes abstraits ===
    { id: 'A1', text: "Placer le mot 'Anticonstitutionnellement' dans une phrase sur la nourriture.", category: 'ABSURD' },
    { id: 'A2', text: "Demander l'heure à quelqu'un tout en regardant votre montre ou téléphone.", category: 'ABSURD' },
    { id: 'A3', text: "S'arrêter brusquement et fixer le plafond avec admiration.", category: 'ABSURD' },
    { id: 'A4', text: "Applaudir une mouche imaginaire pendant 10 secondes.", category: 'ABSURD' },
    { id: 'A5', text: "Vérifier très discrètement sous la table si vos pieds sont toujours là.", category: 'ABSURD' },
    { id: 'A6', text: "Faire semblant de découper votre eau avec un couteau.", category: 'ABSURD' },
    { id: 'A7', text: "Appeler votre verre 'Bernadette' ou 'Gérard'.", category: 'ABSURD' },
    { id: 'A8', text: "Essayer de sentir votre propre épaule discrètement.", category: 'ABSURD' },
    { id: 'A9', text: "Murmurer des mots d'encouragement à votre morceau de pain.", category: 'ABSURD' },
    { id: 'A10', text: "Faire semblant d'attraper quelque chose d'invisible en l'air et le manger.", category: 'ABSURD' },
    { id: 'A11', text: "Parler et bouger au ralenti (slow-motion) pendant 10 secondes.", category: 'ABSURD' },
    { id: 'A12', text: "Demander une paille pour manger vos petits pois.", category: 'ABSURD' },
    { id: 'A13', text: "Mettre votre serviette sur votre épaule comme un perroquet invisible.", category: 'ABSURD' },
    { id: 'A14', text: "S'extasier devant une cuillère : 'Quelle courbe incroyable !'.", category: 'ABSURD' },
    { id: 'A15', text: "Essorer votre serviette sèche au-dessus de votre verre.", category: 'ABSURD' },
    { id: 'A16', text: "Dessiner un visage imaginaire sur la table et lui présenter vos excuses.", category: 'ABSURD' },
    { id: 'A17', text: "Écouter votre verre comme si c'était un coquillage.", category: 'ABSURD' },
    { id: 'A18', text: "Ranger votre fourchette dans votre manche, puis la ressortir l'air de rien.", category: 'ABSURD' },
    { id: 'A19', text: "Souffler sur une glace (ou un truc froid) pour la refroidir.", category: 'ABSURD' },
    { id: 'A20', text: "Demander si le plat contient des 'atomes de bonheur'.", category: 'ABSURD' },
    { id: 'A21', text: "Faire le bruit d'un laser (Pew !) dès que vous pointez un objet.", category: 'ABSURD' },
    { id: 'A22', text: "Vérifier la pointure de votre propre chaussure sous la table.", category: 'ABSURD' },
    { id: 'A23', text: "Dire 'Splash !' chaque fois que vous posez votre verre.", category: 'ABSURD' },
    { id: 'A24', text: "Tenir votre tête avec les deux mains comme si elle allait s'envoler.", category: 'ABSURD' },
    { id: 'A25', text: "Fermer les yeux et annoncer : 'Le chargement est terminé'.", category: 'ABSURD' },
    { id: 'A26', text: "Demander si cette table est compatible avec le format Bluetooth.", category: 'ABSURD' },
    { id: 'A27', text: "Faire des jumelles avec vos mains pour regarder votre interlocuteur.", category: 'ABSURD' },
    { id: 'A28', text: "Dire 'Oh, un glitch !' dès que quelqu'un bafouille.", category: 'ABSURD' },
    { id: 'A29', text: "Appuyer sur votre nez comme si c'était un bouton de sonnette.", category: 'ABSURD' },
    { id: 'A30', text: "Demander si on peut commander de l'eau en version 'sans gluten'.", category: 'ABSURD' },
    { id: 'A31', text: "Se gratter le menton avec le coude (ou essayer).", category: 'ABSURD' },
    { id: 'A32', text: "Dire 'La matrice est instable' si une lumière vacille.", category: 'ABSURD' },
    { id: 'A33', text: "Demander à voir le certificat de naissance de la mayonnaise.", category: 'ABSURD' },
    { id: 'A34', text: "Saluer poliment une chaise vide en arrivant ou en partant.", category: 'ABSURD' },
    { id: 'A35', text: "Mimer un escalator qui descend tout en restant assis.", category: 'ABSURD' },
    { id: 'A36', text: "Dire 'Fin de la transmission' après chaque phrase.", category: 'ABSURD' },
    { id: 'A37', text: "Tapoter la table et dire : 'Elle sonne un peu en Fa mineur, non ?'.", category: 'ABSURD' },
    { id: 'A38', text: "Prendre le pouls de votre bouteille d'eau.", category: 'ABSURD' },
    { id: 'A39', text: "Baptiser officiellement votre verre d'un nom de roi.", category: 'ABSURD' },
    { id: 'A40', text: "Dire 'Le code a changé' quand quelqu'un sort ses clés.", category: 'ABSURD' },
    { id: 'A41', text: "Essayer de faire tenir une miette en équilibre sur votre doigt.", category: 'ABSURD' },
    { id: 'A42', text: "Faire semblant de recevoir un message radio dans vos dents.", category: 'ABSURD' },
    { id: 'A43', text: "Demander si ce dessert existe en version 'Open Source'.", category: 'ABSURD' },
    { id: 'A44', text: "Chercher votre verre alors qu'il est dans votre main.", category: 'ABSURD' },
    { id: 'A45', text: "Faire un bruit de sonar (Bip... Bip...) très bas.", category: 'ABSURD' },
    { id: 'A46', text: "S'excuser auprès de la nappe pour l'avoir froissée.", category: 'ABSURD' },
    { id: 'A47', text: "Lire l'avenir dans une flaque de sauce.", category: 'ABSURD' },
    { id: 'A48', text: "Chuchoter à votre fourchette : 'Ton heure est venue'.", category: 'ABSURD' },
    { id: 'A49', text: "Demander si le vin est compatible avec une montre connectée.", category: 'ABSURD' },
    { id: 'A50', text: "Faire semblant de ramer avec vos bras assis à table.", category: 'ABSURD' },
    { id: 'A51', text: "Vérifier si votre chaise est en mode 'avion'.", category: 'ABSURD' },
    { id: 'A52', text: "Dire 'Chut, elles dorment' en montrant les serviettes.", category: 'ABSURD' },
    { id: 'A53', text: "Essayer d'attraper votre ombre avec une cuillère.", category: 'ABSURD' },
    { id: 'A54', text: "Demander si vous pouvez payer le serveur avec des compliments.", category: 'ABSURD' },
    { id: 'A55', text: "Dire 'Téléchargement de la purée : 45%' pendant que vous mangez.", category: 'ABSURD' },
    { id: 'A56', text: "Faire un clin d'œil à une plante verte.", category: 'ABSURD' },
    { id: 'A57', text: "S'exclamer 'Quel suspense !' avant de soulever votre verre.", category: 'ABSURD' },
    { id: 'A58', text: "Vouloir faire un château de cartes avec des morceaux de pain.", category: 'ABSURD' },
    { id: 'A59', text: "Dire 'Mise en veille' et fermer les yeux pendant 10 secondes.", category: 'ABSURD' },
    { id: 'A60', text: "Demander s'il y a du Wi-Fi dans la salade.", category: 'ABSURD' },
    { id: 'A61', text: "Fixer une bulle dans votre verre comme si c'était un trésor.", category: 'ABSURD' },
    { id: 'A62', text: "Annoncer : 'Attention, je vais changer de fréquence' et parler plus aigu.", category: 'ABSURD' },
    { id: 'A63', text: "Prétendre que votre couteau est une antenne pour capter la radio.", category: 'ABSURD' },
    { id: 'A64', text: "Demander si le pain est d'origine numérique ou biologique.", category: 'ABSURD' },
    { id: 'A65', text: "Faire le bruit du modem 56k dès qu'on vous demande un avis.", category: 'ABSURD' },
    { id: 'A66', text: "Dire 'Accès refusé' quand quelqu'un veut vous prendre une frite.", category: 'ABSURD' },
    { id: 'A67', text: "Regarder à l'intérieur de votre verre avec une mine de détective.", category: 'ABSURD' },
    { id: 'A68', text: "Dire 'Mise à jour système terminée' après avoir bu.", category: 'ABSURD' },
    { id: 'A69', text: "Demander si la chaise supporte le format haute définition.", category: 'ABSURD' },
    { id: 'A70', text: "Essayer de changer de chaîne de télé avec une cuillère.", category: 'ABSURD' },
    { id: 'A71', text: "S'exclamer : 'C'est une attaque par force brute !' en coupant votre viande.", category: 'ABSURD' },
    { id: 'A72', text: "Vérifier si votre serviette a un numéro de série.", category: 'ABSURD' },
    { id: 'A73', text: "Demander si le menu est traduit en langage binaire.", category: 'ABSURD' },
    { id: 'A74', text: "Faire semblant de taper sur un clavier invisible sur la nappe.", category: 'ABSURD' },
    { id: 'A75', text: "Dire 'Vidage du cache' avant de finir votre boisson.", category: 'ABSURD' },
    { id: 'A76', text: "Chercher le numéro de série sous votre assiette.", category: 'ABSURD' },
    { id: 'A77', text: "Remercier la nourriture ou la boisson avant de consommer.", category: 'ABSURD' },
    { id: 'A78', text: "Agir comme un PNJ : répéter la même phrase si on vous touche l'épaule...", category: 'ABSURD' },
    { id: 'A79', text: "Demander s'il y a un mode 'nuit' pour ce plat.", category: 'ABSURD' },
    { id: 'A80', text: "Faire une moue de dégoût chaque fois que quelqu'un dit 'Le'.", category: 'ABSURD' },
    { id: 'A81', text: "Annoncer 'Protocole activé' et poser vos deux mains à plat.", category: 'ABSURD' },
    { id: 'A82', text: "Vérifier si l'eau coule dans le sens des aiguilles d'une montre.", category: 'ABSURD' },
    { id: 'A83', text: "Dire 'Erreur 404' si vous ne trouvez pas le sel.", category: 'ABSURD' },
    { id: 'A84', text: "Demander si le serveur est synchronisé avec l'heure de Tokyo.", category: 'ABSURD' },
    { id: 'A85', text: "Bouger comme un robot qui n'a plus beaucoup de batterie.", category: 'ABSURD' },
    { id: 'A86', text: "Dire 'C'est un bug dans le script' après une fourche linguistique.", category: 'ABSURD' },
    { id: 'A87', text: "Dire que vos chaussures sont des disques durs externes.", category: 'ABSURD' },
    { id: 'A88', text: "Demander si la sauce est compatible avec Linux.", category: 'ABSURD' },
    { id: 'A89', text: "Faire le bruit d'un ventilateur de PC qui surchauffe.", category: 'ABSURD' },
    { id: 'A90', text: "S'exclamer 'Accès autorisé !' en ouvrant une bouteille.", category: 'ABSURD' },
    { id: 'A91', text: "Vérifier si vos oreilles captent la 5G.", category: 'ABSURD' },
    { id: 'A92', text: "Annoncer 'Injection de poivre réussie'.", category: 'ABSURD' },
    { id: 'A93', text: "Plisser les yeux et dire : 'Je scanne la zone'.", category: 'ABSURD' },
    { id: 'A94', text: "Demander si le dessert a une licence Creative Commons.", category: 'ABSURD' },
    { id: 'A95', text: "S'arrêter de parler en plein milieu d'un mot pendant 5 secondes.", category: 'ABSURD' },
    { id: 'A96', text: "Dire 'Passerelle détectée' en regardant la cuisine.", category: 'ABSURD' },
    { id: 'A97', text: "Frotter vos mains et dire 'Optimisation des calories en cours'.", category: 'ABSURD' },
    { id: 'A98', text: "Annoncer 'Synchronisation terminée' après avoir reposé votre verre.", category: 'ABSURD' },
    { id: 'A99', text: "Prétendre que vous êtes en mode 'incognito' et porter votre main devant votre visage.", category: 'ABSURD' },
    { id: 'A100', text: "Se lever et dire 'Fin de session' avant de se rasseoir immédiatement.", category: 'ABSURD' },

    // === RISKY (100) - Espionnage et tension ===
    { id: 'R1', text: "Chuchoter à votre voisin : 'Ils nous observent, fais semblant de rien'.", category: 'RISKY' },
    { id: 'R2', text: "Dire à quelqu'un : 'C'est typiquement ce qu'un agent double dirait'.", category: 'RISKY' },
    { id: 'R3', text: "Demander brusquement : 'Tu n'as pas entendu ce cri ?'.", category: 'RISKY' },
    { id: 'R4', text: "Regarder derrière vous toutes les minutes avec un air inquiet.", category: 'RISKY' },
    { id: 'R5', text: "Chuchoter dans votre propre manche : 'Le colis est arrivé'.", category: 'RISKY' },
    { id: 'R6', text: "Suivre quelqu'un (du regard ou de loin) dès qu'il se déplace.", category: 'RISKY' },
    { id: 'R7', text: "Prendre une photo d'une miette de pain avec un air très sérieux.", category: 'RISKY' },
    { id: 'R8', text: "Changer de sujet de conversation dès que le serveur approche.", category: 'RISKY' },
    { id: 'R9', text: "Demander à voix basse : 'On est vraiment en sécurité ici ?'.", category: 'RISKY' },
    { id: 'R10', text: "Fixer un coin vide de la pièce pendant 30 secondes sans cligner des yeux.", category: 'RISKY' },
    { id: 'R11', text: "Demander à quelqu'un de vous montrer ses paumes de mains.", category: 'RISKY' },
    { id: 'R12', text: "Glisser un morceau de papier plié (vide) sous le verre de quelqu'un.", category: 'RISKY' },
    { id: 'R13', text: "Murmurer 'Cible verrouillée' en regardant une salière.", category: 'RISKY' },
    { id: 'R14', text: "Regarder votre poignet (même sans montre) toutes les 15 secondes.", category: 'RISKY' },
    { id: 'R15', text: "Demander : 'Est-ce que quelqu'un a le mot de passe pour le dessert ?'.", category: 'RISKY' },
    { id: 'R16', text: "Faire semblant de noter quelque chose sur votre serviette avec un stylo imaginaire.", category: 'RISKY' },
    { id: 'R17', text: "Demander à quelqu'un : 'Pour qui travailles-tu réellement ?'.", category: 'RISKY' },
    { id: 'R18', text: "S'approcher de l'oreille de quelqu'un pour murmurer 'C'est validé'.", category: 'RISKY' },
    { id: 'R19', text: "Vérifier s'il n'y a pas un micro caché sous votre propre assiette.", category: 'RISKY' },
    { id: 'R20', text: "Prendre un air grave et dire : 'Le plan B est activé'.", category: 'RISKY' },
    { id: 'R21', text: "Demander : 'Est-ce que cette bouteille d'eau a été scellée devant vous ?'.", category: 'RISKY' },
    { id: 'R22', text: "Faire semblant de recevoir un message crypté sur votre fourchette.", category: 'RISKY' },
    { id: 'R23', text: "Dire 'L'aigle a quitté le nid' quand quelqu'un sort de table.", category: 'RISKY' },
    { id: 'R24', text: "Proposer un échange de serviette de façon très suspecte.", category: 'RISKY' },
    { id: 'R25', text: "Demander si quelqu'un connaît 'Le Renard d'Argent'.", category: 'RISKY' },
    { id: 'R26', text: "Faire un signe de tête complice à quelqu'un à l'autre bout de la pièce.", category: 'RISKY' },
    { id: 'R27', text: "Dire 'Tout se passe comme prévu' après un long silence.", category: 'RISKY' },
    { id: 'R28', text: "Goûter votre boisson avec une prudence extrême, comme si elle était empoisonnée.", category: 'RISKY' },
    { id: 'R29', text: "Demander : 'Qui a envoyé ce signal ?' en regardant votre verre.", category: 'RISKY' },
    { id: 'R30', text: "Faire mine de scanner la nappe avec votre téléphone.", category: 'RISKY' },
    { id: 'R31', text: "Annoncer 'Infiltration réussie' à voix basse.", category: 'RISKY' },
    { id: 'R32', text: "Vérifier si les boutons de chemise de votre voisin ne sont pas des caméras.", category: 'RISKY' },
    { id: 'R33', text: "Demander : 'Est-ce que la cuisine est sous surveillance ?'.", category: 'RISKY' },
    { id: 'R34', text: "Se cacher derrière le menu dès que quelqu'un rit trop fort.", category: 'RISKY' },
    { id: 'R35', text: "Dire 'C'est un piège !' juste avant de manger une bouchée.", category: 'RISKY' },
    { id: 'R36', text: "Faire semblant d'avoir une oreillette et écouter attentivement.", category: 'RISKY' },
    { id: 'R37', text: "Demander si on peut finir la conversation en chuchotant.", category: 'RISKY' },
    { id: 'R38', text: "Soulever le bord de la nappe pour voir ce qu'il y a dessous.", category: 'RISKY' },
    { id: 'R39', text: "Dire 'Données corrompues' après avoir bégayé volontairement.", category: 'RISKY' },
    { id: 'R40', text: "Sentir les couverts avant de les utiliser.", category: 'RISKY' },
    { id: 'R41', text: "Demander : 'Cette zone est-elle sécurisée contre les ondes ?'.", category: 'RISKY' },
    { id: 'R42', text: "Dire 'Activation du mode furtif' et se baisser un peu sur sa chaise.", category: 'RISKY' },
    { id: 'R43', text: "Vérifier si les glaçons ne contiennent pas des objets suspects.", category: 'RISKY' },
    { id: 'R44', text: "Demander à voix basse : 'Où est le point d'extraction ?'.", category: 'RISKY' },
    { id: 'R45', text: "Faire un signe de la main mystérieux vers le plafond.", category: 'RISKY' },
    { id: 'R46', text: "Fixer un objet et dire 'Cible identifiée'.", category: 'RISKY' },
    { id: 'R47', text: "Dire que vous avez mémorisé toutes les sorties de secours.", category: 'RISKY' },
    { id: 'R48', text: "Demander : 'Combien d'agents sont infiltrés ici à votre avis ?'.", category: 'RISKY' },
    { id: 'R49', text: "Annoncer 'Analyse ADN de la frite terminée : elle est saine'.", category: 'RISKY' },
    { id: 'R50', text: "Dire 'Évacuation immédiate !' puis rigoler nerveusement.", category: 'RISKY' },
    { id: 'R51', text: "Demander au verre : 'Où est caché le dossier ?'.", category: 'RISKY' },
    { id: 'R52', text: "Demander à votre voisin s'il a bien reçu 'le signal'.", category: 'RISKY' },
    { id: 'R53', text: "Regarder fixement la caméra (ou le coin du mur) pendant 10 secondes.", category: 'RISKY' },
    { id: 'R54', text: "Dire 'Les loups dorment au garage' sans explication.", category: 'RISKY' },
    { id: 'R55', text: "Vérifier si vos couverts ne sont pas aimantés entre eux.", category: 'RISKY' },
    { id: 'R56', text: "Demander si cette conversation est enregistrée par le gouvernement.", category: 'RISKY' },
    { id: 'R57', text: "Faire semblant de parler à votre montre.", category: 'RISKY' },
    { id: 'R58', text: "Dire 'Le paquet a été livré' après avoir posé votre serviette.", category: 'RISKY' },
    { id: 'R59', text: "Demander à quelqu'un de vérifier s'il n'y a pas un point rouge sur votre front.", category: 'RISKY' },
    { id: 'R60', text: "Dire à votre reflet dans une cuillère : 'Ils ne sauront jamais'.", category: 'RISKY' },
    { id: 'R61', text: "Peser votre fourchette dans votre main avec un air d'expert.", category: 'RISKY' },
    { id: 'R62', text: "Dire 'Il y a une faille dans le périmètre'.", category: 'RISKY' },
    { id: 'R63', text: "Demander si le serveur porte une perruque.", category: 'RISKY' },
    { id: 'R64', text: "Mettre vos mains autour de votre téléphone pour 'brouiller les ondes'.", category: 'RISKY' },
    { id: 'R65', text: "Dire 'C'est une mission sans retour' avant d'entamer le dessert.", category: 'RISKY' },
    { id: 'R66', text: "Murmurer 'Alpha, ici Tango, j'ai faim, répondez'.", category: 'RISKY' },
    { id: 'R67', text: "Demander si ce plat a été 'approuvé par le conseil'.", category: 'RISKY' },
    { id: 'R68', text: "Faire semblant d'avoir un bouton secret sous la table.", category: 'RISKY' },
    { id: 'R69', text: "Dire 'L'ombre va tomber' d'un ton très prophétique.", category: 'RISKY' },
    { id: 'R70', text: "Vérifier si la nappe ne cache pas un clavier.", category: 'RISKY' },
    { id: 'R71', text: "Demander : 'Qui ici est payé pour nous surveiller ?'.", category: 'RISKY' },
    { id: 'R72', text: "Mimer le désamorçage d'une bombe avec une salière.", category: 'RISKY' },
    { id: 'R73', text: "Dire 'Le signal est faible' et pencher la tête sur le côté.", category: 'RISKY' },
    { id: 'R74', text: "Demander si le serveur est un androïde.", category: 'RISKY' },
    { id: 'R75', text: "Dire 'Ordre prioritaire reçu' et changer de façon de s'asseoir.", category: 'RISKY' },
    { id: 'R76', text: "Chuchoter : 'Ne fais confiance à personne, surtout pas au sel'.", category: 'RISKY' },
    { id: 'R77', text: "Regarder les empreintes digitales sur votre verre avec une loupe imaginaire.", category: 'RISKY' },
    { id: 'R78', text: "Demander : 'Avez-vous vu l'homme en gris ?'.", category: 'RISKY' },
    { id: 'R79', text: "Faire semblant de prendre une photo discrète sous la table.", category: 'RISKY' },
    { id: 'R80', text: "Dire 'C'est une opération sous couverture'.", category: 'RISKY' },
    { id: 'R81', text: "Dire que vous avez un traducteur universel dans votre oreille.", category: 'RISKY' },
    { id: 'R82', text: "Demander le plan d'évacuation en cas d'invasion de canards.", category: 'RISKY' },
    { id: 'R83', text: "Faire semblant de voir à travers les murs.", category: 'RISKY' },
    { id: 'R84', text: "Dire 'Le protocole Omega est maintenant actif'.", category: 'RISKY' },
    { id: 'R85', text: "Vérifier si le pain ne contient pas de message caché.", category: 'RISKY' },
    { id: 'R86', text: "Demander si cette viande est 'bio-synthétique'.", category: 'RISKY' },
    { id: 'R87', text: "Noter des chiffres imaginaires sur la buée de votre verre.", category: 'RISKY' },
    { id: 'R88', text: "Dire 'Le temps joue contre nous' en regardant une miette.", category: 'RISKY' },
    { id: 'R89', text: "Dire 'Ils sont là...' puis se taire brusquement pendant 10 secondes.", category: 'RISKY' },
    { id: 'R90', text: "Demander : 'As-tu le carnet rouge ?'.", category: 'RISKY' },
    { id: 'R91', text: "Mimer une liaison satellite avec vos doigts sur votre tempe.", category: 'RISKY' },
    { id: 'R92', text: "Dire 'Rupture de confinement' si quelqu'un ouvre une bouteille.", category: 'RISKY' },
    { id: 'R93', text: "Vérifier si votre chaise n'a pas été permutée.", category: 'RISKY' },
    { id: 'R94', text: "Demander : 'Où est le dossier Delta ?'.", category: 'RISKY' },
    { id: 'R95', text: "Mimer l'analyse de l'air avec vos doigts.", category: 'RISKY' },
    { id: 'R96', text: "Dire 'Le compte à rebours a commencé' et compter de 10 à 0 très bas.", category: 'RISKY' },
    { id: 'R97', text: "Regarder le bouchon de la bouteille comme si c'était un explosif.", category: 'RISKY' },
    { id: 'R98', text: "Demander : 'As-tu ton badge de niveau 4 ?'.", category: 'RISKY' },
    { id: 'R99', text: "Reculer lentement de la table avec un air suspect.", category: 'RISKY' },
    { id: 'R100', text: "Dire 'Mission accomplie' en posant votre serviette à la fin.", category: 'RISKY' }
];