export interface Challenge {
    id: string;
    text: string;
}

export const CHALLENGES: Challenge[] = [
    // === SOCIAL (100) - Décalages de comportement et petites gênes ===
    { id: 'S1', text: "Faire un compliment très spécifique sur la symétrie du visage de quelqu'un." },
    { id: 'S2', text: "Se toucher l'oreille gauche 3 fois dès que vous prenez la parole." },
    { id: 'S3', text: "Bailler bruyamment, puis s'arrêter net en fixant quelqu'un." },
    { id: 'S4', text: "Répéter la dernière phrase de votre interlocuteur sous forme de question." },
    { id: 'S5', text: "Siffler un air très connu mais très doucement pendant un silence." },
    { id: 'S6', text: "Changer de place avec quelqu'un sans donner de raison valable." },
    { id: 'S7', text: "Applaudir très brièvement après qu'une personne ait fini de boire." },
    { id: 'S8', text: "Demander à quelqu'un s'il n'a pas l'impression que la pièce penche vers la gauche." },
    { id: 'S9', text: "Faire un clin d'œil appuyé après avoir dit une phrase banale comme 'Il fait beau'." },
    { id: 'S10', text: "Parler de votre passion pour les élevages de phasmes pendant 1 minute." },
    { id: 'S11', text: "Demander à quelqu'un de vous tenir votre verre 'juste deux secondes' sans bouger." },
    { id: 'S12', text: "Rire de bon cœur à une phrase qui n'était absolument pas une blague." },
    { id: 'S13', text: "Proposer un toast : 'À la santé des girafes et de leur long cou'." },
    { id: 'S14', text: "Demander à quelqu'un s'il n'a pas un 'nuage de charisme' au-dessus de la tête." },
    { id: 'S15', text: "S'excuser platement auprès d'une fourchette après l'avoir fait tomber." },
    { id: 'S16', text: "Demander le prénom d'une personne que vous connaissez depuis des années." },
    { id: 'S17', text: "Redire 'Enchanté' à la même personne pour la troisième fois du repas." },
    { id: 'S18', text: "Demander conseil sur la manière 'la plus élégante' de poser ses mains sur la table." },
    { id: 'S19', text: "Féliciter quelqu'un avec beaucoup de sérieux après qu'il ait utilisé un mot de plus de trois syllabes." },
    { id: 'S20', text: "Regarder fixement le front de la personne qui vous parle." },
    { id: 'S21', text: "Appeler quelqu'un par le nom d'un personnage de film pendant 2 minutes." },
    { id: 'S22', text: "Proposer de lire l'avenir dans les lignes de la main avec beaucoup de sérieux." },
    { id: 'S23', text: "Dire 'C'est fou ça...' après chaque phrase de votre voisin." },
    { id: 'S24', text: "Demander à voix basse : 'Est-ce que vous aussi vous sentez cette odeur de pop-corn ?'." },
    { id: 'S25', text: "Avoir un hoquet très sonore, une seule fois, de façon très théâtrale." },
    { id: 'S26', text: "Essayer de parler sans jamais utiliser de mots contenant la lettre 'R'." },
    { id: 'S27', text: "Demander l'avis du groupe sur : 'Quelle est la meilleure forme de pâtes ?'." },
    { id: 'S28', text: "Prétendre que vous avez un oncle qui a inventé le bouton de chemise." },
    { id: 'S29', text: "Dire 'Chut !' en regardant le plafond, puis reprendre la discussion." },
    { id: 'S30', text: "Prendre un accent très léger et indéfinissable pendant trois phrases." },
    { id: 'S31', text: "Demander si quelqu'un a une solution contre les 'fourmis dans les sourcils'." },
    { id: 'S32', text: "Initier un check complexe qui finit en Pierre-Feuille-Ciseaux." },
    { id: 'S33', text: "Raconter une anecdote sur une pomme de terre qui n'a pas de fin." },
    { id: 'S34', text: "Dire 'Tu n'aurais pas dû dire ça...' avec un regard mystérieux." },
    { id: 'S35', text: "Faire épeler son propre prénom à quelqu'un, très lentement." },
    { id: 'S36', text: "Remplacer le mot 'Chaise' par 'Le support de gravité personnel'." },
    { id: 'S37', text: "S'exclamer 'La prophétie !' apès une action d'un autre joueur." },
    { id: 'S38', text: "Demander très sérieusement : 'Tu penses que les poissons ont soif ?'." },
    { id: 'S39', text: "Sautiller une fois sur place avant de vous rasseoir." },
    { id: 'S40', text: "Dire 'Exactement !' en pointant du doigt quelqu'un qui n'a rien dit." },
    { id: 'S41', text: "Lancer un concours de celui qui cligne des yeux en dernier." },
    { id: 'S42', text: "Prétendre que vous entendez un sifflement que personne d'autre n'entend." },
    { id: 'S43', text: "Demander à votre voisin s'il peut vous aider à 'ranger votre aura'." },
    { id: 'S44', text: "Débattre avec ferveur : 'Faut-il mettre les céréales avant ou après le lait ?'." },
    { id: 'S45', text: "Dire que vous avez une peur panique des genoux (la génuphobie)." },
    { id: 'S46', text: "Comparer le rire de quelqu'un au chant d'un oiseau rare (en compliment)." },
    { id: 'S47', text: "Simuler une conversation téléphonique très courte avec votre main (sans téléphone)." },
    { id: 'S48', text: "Chercher un objet imaginaire sur la table pendant 30 secondes." },
    { id: 'S49', text: "Dire 'Bingo !la prochaine fois que quelqu'un dit le mot 'Oui'." },
    { id: 'S50', text: "Proposer de renommer les jours de la semaine par des noms de navigateurs célèbres." },
    { id: 'S51', text: "Se frotter les mains énergiquement avant de toucher vos couverts." },
    { id: 'S52', text: "Demander : 'Est-ce que vous trouvez que les tables sont trop horizontales ?'." },
    { id: 'S53', text: "Affirmer que vous parlez couramment le langage des yeux." },
    { id: 'S54', text: "Répondre 'C'est pas faux' à tout ce qu'on vous dit pendant 2 minutes." },
    { id: 'S55', text: "Prétendre que vous avez un flash du futur concernant le dessert." },
    { id: 'S56', text: "Demander à quelqu'un s'il veut votre autographe sur sa serviette." },
    { id: 'S57', text: "Dire 'Oups, mon autre moi prend le dessus' après un éternuement." },
    { id: 'S58', text: "Essayer de faire une tour avec les morceaux de pain sur la table." },
    { id: 'S59', text: "Demander si vous pouvez 'emprunter une émotion' à quelqu'un." },
    { id: 'S60', text: "Dire 'C'est noté' d'un air très sérieux après une phrase banale." },
    { id: 'S61', text: "S'asseoir sur le bord extrême de sa chaise comme si on allait s'envoler." },
    { id: 'S62', text: "Demander à la ronde : 'Qui croit aux chats télépathes ?'." },
    { id: 'S63', text: "Faire semblant d'avoir un troisième bras invisible pour porter votre verre." },
    { id: 'S64', text: "Dire 'Visez la lune !' au milieu d'un silence total." },
    { id: 'S65', text: "Proposer de créer un fan-club pour le sel de table." },
    { id: 'S66', text: "Demander : 'Tu as payé ta taxe sur l'humour aujourd'hui ?'." },
    { id: 'S67', text: "Dire 'Maudit soit ce jambon' sans raison particulière." },
    { id: 'S68', text: "Taper un rythme sur la table et dire : 'C'est du Morse pour : j'ai faim'." },
    { id: 'S69', text: "Demander à quelqu'un de surveiller votre ombre deux minutes." },
    { id: 'S70', text: "Deviner le signe astrologique de tout le monde (et se tromper volontairement)." },
    { id: 'S71', text: "Faire semblant d'être allergique au mot 'Précisément'." },
    { id: 'S72', text: "S'émerveiller devant la réfraction de la lumière dans votre verre." },
    { id: 'S73', text: "Dire 'Il était temps qu'on en vienne au fait' après qu'on vous ait demandé le sel." },
    { id: 'S74', text: "Lancer une Ola tout seul, avec enthousiasme." },
    { id: 'S75', text: "Demander : 'Tu penses qu'on peut faire du ski sur de la purée ?'." },
    { id: 'S76', text: "Crier 'Alerte rouge !' si une goutte d'eau tombe sur la nappe." },
    { id: 'S77', text: "Prétendre que vous collectionnez les enregistrements de bruits de klaxons." },
    { id: 'S78', text: "Demander à quelqu'un s'il a le numéro de téléphone du Père Noël." },
    { id: 'S79', text: "Dire 'Je savais que tu dirais ça' à chaque fois que quelqu'un parle." },
    { id: 'S80', text: "Faire un solo de 'Air Piano' sur le bord de la table." },
    { id: 'S81', text: "Demander : 'Est-ce que vous voyez aussi ce petit reflet sur l'épaule de Paul ?'." },
    { id: 'S82', text: "Finir vos phrases par '... et c'est mon dernier mot !'." },
    { id: 'S83', text: "Confier un faux secret : 'Je ne sais pas nager avec des chaussettes'." },
    { id: 'S84', text: "Demander quelle est la différence entre un canard (ne pas finir la phrase)." },
    { id: 'S85', text: "S'exclamer 'Eurêka !' et pointer une miette de pain." },
    { id: 'S86', text: "Proposer de renommer le lundi 'Le Grand Sommeil'." },
    { id: 'S87', text: "Demander : 'Quelqu'un a vu mon enthousiasme ? Je l'ai posé là'." },
    { id: 'S88', text: "Dire 'C'est lunaire !' dès que quelqu'un sourit." },
    { id: 'S89', text: "Prétendre que vous avez un talent pour deviner le prix des objets au toucher." },
    { id: 'S90', text: "Vérifier si les coudes de votre voisin sont 'parallèles au sol'." },
    { id: 'S91', text: "Dire 'Mince alors' dès que quelqu'un pose un couvert sur la table." },
    { id: 'S92', text: "Demander une minute de silence pour la fin du plat principal." },
    { id: 'S93', text: "Demander si quelqu'un a déjà vu un pigeon faire du breakdance." },
    { id: 'S94', text: "Affirmer que les cafetières complotent contre le thé." },
    { id: 'S95', text: "Prétendre que vous savez lire dans les pensées des olives." },
    { id: 'S96', text: "Demander : 'C'est quoi votre plan B si la gravité s'arrête ?'." },
    { id: 'S97', text: "Dire 'Attention, le chef arrive !' et se tenir très droit." },
    { id: 'S98', text: "Organiser un vote pour élire la 'meilleure fourchette du lot'." },
    { id: 'S99', text: "Demander : 'Tu préférerais avoir des mains à la place des pieds ou l'inverse ?'." },
    { id: 'S100', text: "Dire 'Et voilà le travail !' après avoir simplement respiré fort." },

    // === ABSURD (100) - Délires technologiques et gestes abstraits ===
    { id: 'A1', text: "Placer le mot 'Anticonstitutionnellement' dans une phrase sur la nourriture." },
    { id: 'A2', text: "Demander l'heure à quelqu'un tout en regardant votre montre ou téléphone." },
    { id: 'A3', text: "S'arrêter brusquement et fixer le plafond avec admiration." },
    { id: 'A4', text: "Applaudir une mouche imaginaire pendant 10 secondes." },
    { id: 'A5', text: "Vérifier très discrètement sous la table si vos pieds sont toujours là." },
    { id: 'A6', text: "Faire semblant de découper votre eau avec un couteau." },
    { id: 'A7', text: "Appeler votre verre 'Bernadette' ou 'Gérard'." },
    { id: 'A8', text: "Essayer de sentir votre propre épaule discrètement." },
    { id: 'A9', text: "Murmurer des mots d'encouragement à votre morceau de pain." },
    { id: 'A10', text: "Faire semblant d'attraper quelque chose d'invisible en l'air et le manger." },
    { id: 'A11', text: "Parler et bouger au ralenti (slow-motion) pendant 10 secondes." },
    { id: 'A12', text: "Demander une paille pour manger vos petits pois." },
    { id: 'A13', text: "Mettre votre serviette sur votre épaule comme un perroquet invisible." },
    { id: 'A14', text: "S'extasier devant une cuillère : 'Quelle courbe incroyable !'." },
    { id: 'A15', text: "Essorer votre serviette sèche au-dessus de votre verre." },
    { id: 'A16', text: "Dessiner un visage imaginaire sur la table et lui présenter vos excuses." },
    { id: 'A17', text: "Écouter votre verre comme si c'était un coquillage." },
    { id: 'A18', text: "Ranger votre fourchette dans votre manche, puis la ressortir l'air de rien." },
    { id: 'A19', text: "Souffler sur une glace (ou un truc froid) pour la refroidir." },
    { id: 'A20', text: "Demander si le plat contient des 'atomes de bonheur'." },
    { id: 'A21', text: "Faire le bruit d'un laser (Pew !) dès que vous pointez un objet." },
    { id: 'A22', text: "Vérifier la pointure de votre propre chaussure sous la table." },
    { id: 'A23', text: "Dire 'Splash !' chaque fois que vous posez votre verre." },
    { id: 'A24', text: "Tenir votre tête avec les deux mains comme si elle allait s'envoler." },
    { id: 'A25', text: "Fermer les yeux et annoncer : 'Le chargement est terminé'." },
    { id: 'A26', text: "Demander si cette table est compatible avec le format Bluetooth." },
    { id: 'A27', text: "Faire des jumelles avec vos mains pour regarder votre interlocuteur." },
    { id: 'A28', text: "Dire 'Oh, un glitch !' dès que quelqu'un bafouille." },
    { id: 'A29', text: "Appuyer sur votre nez comme si c'était un bouton de sonnette." },
    { id: 'A30', text: "Demander si on peut commander de l'eau en version 'sans gluten'." },
    { id: 'A31', text: "Se gratter le menton avec le coude (ou essayer)." },
    { id: 'A32', text: "Dire 'La matrice est instable' si une lumière vacille." },
    { id: 'A33', text: "Demander à voir le certificat de naissance de la mayonnaise." },
    { id: 'A34', text: "Saluer poliment une chaise vide en arrivant ou en partant." },
    { id: 'A35', text: "Mimer un escalator qui descend tout en restant assis." },
    { id: 'A36', text: "Dire 'Fin de la transmission' après chaque phrase." },
    { id: 'A37', text: "Tapoter la table et dire : 'Elle sonne un peu en Fa mineur, non ?'." },
    { id: 'A38', text: "Prendre le pouls de votre bouteille d'eau." },
    { id: 'A39', text: "Baptiser officiellement votre verre d'un nom de roi." },
    { id: 'A40', text: "Dire 'Le code a changé' quand quelqu'un sort ses clés." },
    { id: 'A41', text: "Essayer de faire tenir une miette en équilibre sur votre doigt." },
    { id: 'A42', text: "Faire semblant de recevoir un message radio dans vos dents." },
    { id: 'A43', text: "Demander si ce dessert existe en version 'Open Source'." },
    { id: 'A44', text: "Chercher votre verre alors qu'il est dans votre main." },
    { id: 'A45', text: "Faire un bruit de sonar (Bip... Bip...) très bas." },
    { id: 'A46', text: "S'excuser auprès de la nappe pour l'avoir froissée." },
    { id: 'A47', text: "Lire l'avenir dans une flaque de sauce." },
    { id: 'A48', text: "Chuchoter à votre fourchette : 'Ton heure est venue'." },
    { id: 'A49', text: "Demander si le vin est compatible avec une montre connectée." },
    { id: 'A50', text: "Faire semblant de ramer avec vos bras assis à table." },
    { id: 'A51', text: "Vérifier si votre chaise est en mode 'avion'." },
    { id: 'A52', text: "Dire 'Chut, elles dorment' en montrant les serviettes." },
    { id: 'A53', text: "Essayer d'attraper votre ombre avec une cuillère." },
    { id: 'A54', text: "Demander si vous pouvez payer le serveur avec des compliments." },
    { id: 'A55', text: "Dire 'Téléchargement de la purée : 45%' pendant que vous mangez." },
    { id: 'A56', text: "Faire un clin d'œil à une plante verte." },
    { id: 'A57', text: "S'exclamer 'Quel suspense !' avant de soulever votre verre." },
    { id: 'A58', text: "Vouloir faire un château de cartes avec des morceaux de pain." },
    { id: 'A59', text: "Dire 'Mise en veille' et fermer les yeux pendant 10 secondes." },
    { id: 'A60', text: "Demander s'il y a du Wi-Fi dans la salade." },
    { id: 'A61', text: "Fixer une bulle dans votre verre comme si c'était un trésor." },
    { id: 'A62', text: "Annoncer : 'Attention, je vais changer de fréquence' et parler plus aigu." },
    { id: 'A63', text: "Prétendre que votre couteau est une antenne pour capter la radio." },
    { id: 'A64', text: "Demander si le pain est d'origine numérique ou biologique." },
    { id: 'A65', text: "Faire le bruit du modem 56k dès qu'on vous demande un avis." },
    { id: 'A66', text: "Dire 'Accès refusé' quand quelqu'un veut vous prendre une frite." },
    { id: 'A67', text: "Regarder à l'intérieur de votre verre avec une mine de détective." },
    { id: 'A68', text: "Dire 'Mise à jour système terminée' après avoir bu." },
    { id: 'A69', text: "Demander si la chaise supporte le format haute définition." },
    { id: 'A70', text: "Essayer de changer de chaîne de télé avec une cuillère." },
    { id: 'A71', text: "S'exclamer : 'C'est une attaque par force brute !' en coupant votre viande." },
    { id: 'A72', text: "Vérifier si votre serviette a un numéro de série." },
    { id: 'A73', text: "Demander si le menu est traduit en langage binaire." },
    { id: 'A74', text: "Faire semblant de taper sur un clavier invisible sur la nappe." },
    { id: 'A75', text: "Dire 'Vidage du cache' avant de finir votre boisson." },
    { id: 'A76', text: "Chercher le numéro de série sous votre assiette." },
    { id: 'A77', text: "Remercier la nourriture ou la boisson avant de consommer." },
    { id: 'A78', text: "Agir comme un PNJ : répéter la même phrase si on vous touche l'épaule..." },
    { id: 'A79', text: "Demander s'il y a un mode 'nuit' pour ce plat." },
    { id: 'A80', text: "Faire une moue de dégoût chaque fois que quelqu'un dit 'Le'." },
    { id: 'A81', text: "Annoncer 'Protocole activé' et poser vos deux mains à plat." },
    { id: 'A82', text: "Vérifier si l'eau coule dans le sens des aiguilles d'une montre." },
    { id: 'A83', text: "Dire 'Erreur 404' si vous ne trouvez pas le sel." },
    { id: 'A84', text: "Demander si le serveur est synchronisé avec l'heure de Tokyo." },
    { id: 'A85', text: "Bouger comme un robot qui n'a plus beaucoup de batterie." },
    { id: 'A86', text: "Dire 'C'est un bug dans le script' après une fourche linguistique." },
    { id: 'A87', text: "Dire que vos chaussures sont des disques durs externes." },
    { id: 'A88', text: "Demander si la sauce est compatible avec Linux." },
    { id: 'A89', text: "Faire le bruit d'un ventilateur de PC qui surchauffe." },
    { id: 'A90', text: "S'exclamer 'Accès autorisé !' en ouvrant une bouteille." },
    { id: 'A91', text: "Vérifier si vos oreilles captent la 5G." },
    { id: 'A92', text: "Annoncer 'Injection de poivre réussie'." },
    { id: 'A93', text: "Plisser les yeux et dire : 'Je scanne la zone'." },
    { id: 'A94', text: "Demander si le dessert a une licence Creative Commons." },
    { id: 'A95', text: "S'arrêter de parler en plein milieu d'un mot pendant 5 secondes." },
    { id: 'A96', text: "Dire 'Passerelle détectée' en regardant la cuisine." },
    { id: 'A97', text: "Frotter vos mains et dire 'Optimisation des calories en cours'." },
    { id: 'A98', text: "Annoncer 'Synchronisation terminée' après avoir reposé votre verre." },
    { id: 'A99', text: "Prétendre que vous êtes en mode 'incognito' et porter votre main devant votre visage." },
    { id: 'A100', text: "Se lever et dire 'Fin de session' avant de se rasseoir immédiatement." },

    // === RISKY (100) - Espionnage et tension ===
    { id: 'R1', text: "Chuchoter à votre voisin : 'Ils nous observent, fais semblant de rien'." },
    { id: 'R2', text: "Dire à quelqu'un : 'C'est typiquement ce qu'un agent double dirait'." },
    { id: 'R3', text: "Demander brusquement : 'Tu n'as pas entendu ce cri ?'." },
    { id: 'R4', text: "Regarder derrière vous toutes les minutes avec un air inquiet." },
    { id: 'R5', text: "Chuchoter dans votre propre manche : 'Le colis est arrivé'." },
    { id: 'R6', text: "Suivre quelqu'un (du regard ou de loin) dès qu'il se déplace." },
    { id: 'R7', text: "Prendre une photo d'une miette de pain avec un air très sérieux." },
    { id: 'R8', text: "Changer de sujet de conversation dès que le serveur approche." },
    { id: 'R9', text: "Demander à voix basse : 'On est vraiment en sécurité ici ?'." },
    { id: 'R10', text: "Fixer un coin vide de la pièce pendant 30 secondes sans cligner des yeux." },
    { id: 'R11', text: "Demander à quelqu'un de vous montrer ses paumes de mains." },
    { id: 'R12', text: "Glisser un morceau de papier plié (vide) sous le verre de quelqu'un." },
    { id: 'R13', text: "Murmurer 'Cible verrouillée' en regardant une salière." },
    { id: 'R14', text: "Regarder votre poignet (même sans montre) toutes les 15 secondes." },
    { id: 'R15', text: "Demander : 'Est-ce que quelqu'un a le mot de passe pour le dessert ?'." },
    { id: 'R16', text: "Faire semblant de noter quelque chose sur votre serviette avec un stylo imaginaire." },
    { id: 'R17', text: "Demander à quelqu'un : 'Pour qui travailles-tu réellement ?'." },
    { id: 'R18', text: "S'approcher de l'oreille de quelqu'un pour murmurer 'C'est validé'." },
    { id: 'R19', text: "Vérifier s'il n'y a pas un micro caché sous votre propre assiette." },
    { id: 'R20', text: "Prendre un air grave et dire : 'Le plan B est activé'." },
    { id: 'R21', text: "Demander : 'Est-ce que cette bouteille d'eau a été scellée devant vous ?'." },
    { id: 'R22', text: "Faire semblant de recevoir un message crypté sur votre fourchette." },
    { id: 'R23', text: "Dire 'L'aigle a quitté le nid' quand quelqu'un sort de table." },
    { id: 'R24', text: "Proposer un échange de serviette de façon très suspecte." },
    { id: 'R25', text: "Demander si quelqu'un connaît 'Le Renard d'Argent'." },
    { id: 'R26', text: "Faire un signe de tête complice à quelqu'un à l'autre bout de la pièce." },
    { id: 'R27', text: "Dire 'Tout se passe comme prévu' après un long silence." },
    { id: 'R28', text: "Goûter votre boisson avec une prudence extrême, comme si elle était empoisonnée." },
    { id: 'R29', text: "Demander : 'Qui a envoyé ce signal ?' en regardant votre verre." },
    { id: 'R30', text: "Faire mine de scanner la nappe avec votre téléphone." },
    { id: 'R31', text: "Annoncer 'Infiltration réussie' à voix basse." },
    { id: 'R32', text: "Vérifier si les boutons de chemise de votre voisin ne sont pas des caméras." },
    { id: 'R33', text: "Demander : 'Est-ce que la cuisine est sous surveillance ?'." },
    { id: 'R34', text: "Se cacher derrière le menu dès que quelqu'un rit trop fort." },
    { id: 'R35', text: "Dire 'C'est un piège !' juste avant de manger une bouchée." },
    { id: 'R36', text: "Faire semblant d'avoir une oreillette et écouter attentivement." },
    { id: 'R37', text: "Demander si on peut finir la conversation en chuchotant." },
    { id: 'R38', text: "Soulever le bord de la nappe pour voir ce qu'il y a dessous." },
    { id: 'R39', text: "Dire 'Données corrompues' après avoir bégayé volontairement." },
    { id: 'R40', text: "Sentir les couverts avant de les utiliser." },
    { id: 'R41', text: "Demander : 'Cette zone est-elle sécurisée contre les ondes ?'." },
    { id: 'R42', text: "Dire 'Activation du mode furtif' et se baisser un peu sur sa chaise." },
    { id: 'R43', text: "Vérifier si les glaçons ne contiennent pas des objets suspects." },
    { id: 'R44', text: "Demander à voix basse : 'Où est le point d'extraction ?'." },
    { id: 'R45', text: "Faire un signe de la main mystérieux vers le plafond." },
    { id: 'R46', text: "Fixer un objet et dire 'Cible identifiée'." },
    { id: 'R47', text: "Dire que vous avez mémorisé toutes les sorties de secours." },
    { id: 'R48', text: "Demander : 'Combien d'agents sont infiltrés ici à votre avis ?'." },
    { id: 'R49', text: "Annoncer 'Analyse ADN de la frite terminée : elle est saine'." },
    { id: 'R50', text: "Dire 'Évacuation immédiate !' puis rigoler nerveusement." },
    { id: 'R51', text: "Demander au verre : 'Où est caché le dossier ?'." },
    { id: 'R52', text: "Demander à votre voisin s'il a bien reçu 'le signal'." },
    { id: 'R53', text: "Regarder fixement la caméra (ou le coin du mur) pendant 10 secondes." },
    { id: 'R54', text: "Dire 'Les loups dorment au garage' sans explication." },
    { id: 'R55', text: "Vérifier si vos couverts ne sont pas aimantés entre eux." },
    { id: 'R56', text: "Demander si cette conversation est enregistrée par le gouvernement." },
    { id: 'R57', text: "Faire semblant de parler à votre montre." },
    { id: 'R58', text: "Dire 'Le paquet a été livré' après avoir posé votre serviette." },
    { id: 'R59', text: "Demander à quelqu'un de vérifier s'il n'y a pas un point rouge sur votre front." },
    { id: 'R60', text: "Dire à votre reflet dans une cuillère : 'Ils ne sauront jamais'." },
    { id: 'R61', text: "Peser votre fourchette dans votre main avec un air d'expert." },
    { id: 'R62', text: "Dire 'Il y a une faille dans le périmètre'." },
    { id: 'R63', text: "Demander si le serveur porte une perruque." },
    { id: 'R64', text: "Mettre vos mains autour de votre téléphone pour 'brouiller les ondes'." },
    { id: 'R65', text: "Dire 'C'est une mission sans retour' avant d'entamer le dessert." },
    { id: 'R66', text: "Murmurer 'Alpha, ici Tango, j'ai faim, répondez'." },
    { id: 'R67', text: "Demander si ce plat a été 'approuvé par le conseil'." },
    { id: 'R68', text: "Faire semblant d'avoir un bouton secret sous la table." },
    { id: 'R69', text: "Dire 'L'ombre va tomber' d'un ton très prophétique." },
    { id: 'R70', text: "Vérifier si la nappe ne cache pas un clavier." },
    { id: 'R71', text: "Demander : 'Qui ici est payé pour nous surveiller ?'." },
    { id: 'R72', text: "Mimer le désamorçage d'une bombe avec une salière." },
    { id: 'R73', text: "Dire 'Le signal est faible' et pencher la tête sur le côté." },
    { id: 'R74', text: "Demander si le serveur est un androïde." },
    { id: 'R75', text: "Dire 'Ordre prioritaire reçu' et changer de façon de s'asseoir." },
    { id: 'R76', text: "Chuchoter : 'Ne fais confiance à personne, surtout pas au sel'." },
    { id: 'R77', text: "Regarder les empreintes digitales sur votre verre avec une loupe imaginaire." },
    { id: 'R78', text: "Demander : 'Avez-vous vu l'homme en gris ?'." },
    { id: 'R79', text: "Faire semblant de prendre une photo discrète sous la table." },
    { id: 'R80', text: "Dire 'C'est une opération sous couverture'." },
    { id: 'R81', text: "Dire que vous avez un traducteur universel dans votre oreille." },
    { id: 'R82', text: "Demander le plan d'évacuation en cas d'invasion de canards." },
    { id: 'R83', text: "Faire semblant de voir à travers les murs." },
    { id: 'R84', text: "Dire 'Le protocole Omega est maintenant actif'." },
    { id: 'R85', text: "Vérifier si le pain ne contient pas de message caché." },
    { id: 'R86', text: "Demander si cette viande est 'bio-synthétique'." },
    { id: 'R87', text: "Noter des chiffres imaginaires sur la buée de votre verre." },
    { id: 'R88', text: "Dire 'Le temps joue contre nous' en regardant une miette." },
    { id: 'R89', text: "Dire 'Ils sont là...' puis se taire brusquement pendant 10 secondes." },
    { id: 'R90', text: "Demander : 'As-tu le carnet rouge ?'." },
    { id: 'R91', text: "Mimer une liaison satellite avec vos doigts sur votre tempe." },
    { id: 'R92', text: "Dire 'Rupture de confinement' si quelqu'un ouvre une bouteille." },
    { id: 'R93', text: "Vérifier si votre chaise n'a pas été permutée." },
    { id: 'R94', text: "Demander : 'Où est le dossier Delta ?'." },
    { id: 'R95', text: "Mimer l'analyse de l'air avec vos doigts." },
    { id: 'R96', text: "Dire 'Le compte à rebours a commencé' et compter de 10 à 0 très bas." },
    { id: 'R97', text: "Regarder le bouchon de la bouteille comme si c'était un explosif." },
    { id: 'R98', text: "Demander : 'As-tu ton badge de niveau 4 ?'." },
    { id: 'R99', text: "Reculer lentement de la table avec un air suspect." },
    { id: 'R100', text: "Dire 'Mission accomplie' en posant votre serviette à la fin." }
];