import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  rouletteOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
    zIndex: 99999,
    justifyContent: "center",
    alignItems: "center",
    elevation: 100,
  },
  rouletteContainer: {
    width: "100%",
    maxWidth: 1100,
    marginHorizontal: "auto",
    alignItems: "center",
    padding: 30,
    marginTop: -50,
  },
  rouletteHeader: {
    alignItems: "center",
    marginBottom: 40,
  },
  rouletteTitle: {
    fontSize: 18,
    color: "#FF6B6B",
    marginTop: 15,
    letterSpacing: 4,
    textAlign: "center",
    textShadowColor: "rgba(255, 107, 107, 0.5)",
    textShadowRadius: 10,
  },
  rouletteSub: {
    fontSize: 10,
    color: "rgba(255,255,255,0.6)",
    marginTop: 8,
    letterSpacing: 2,
    textTransform: "uppercase",
    textAlign: "center",
  },
  rouletteBox: {
    width: "95%",
    height: 140,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderWidth: 2,
    borderColor: "rgba(255, 107, 107, 0.3)",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    overflow: "hidden",
    shadowColor: "#FF6B6B",
    shadowOpacity: 0.2,
    shadowRadius: 20,
  },
  rouletteMarker: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 35,
    height: 70,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderColor: "#FF6B6B",
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    zIndex: 1,
  },
  rouletteNames: {
    width: "100%",
    zIndex: 2,
  },
  winnerTag: {
    marginTop: 50,
    paddingHorizontal: 30,
    paddingVertical: 15,
    backgroundColor: "rgba(255, 107, 107, 0.2)",
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#FF6B6B",
    shadowColor: "#FF6B6B",
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  winnerName: {
    fontSize: 14,
    color: "#FFF",
    letterSpacing: 2,
    fontWeight: "bold",
    textAlign: "center",
  },
});
