import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  cardContainer: {
    marginBottom: 40,
    borderRadius: 15,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  terminalHeader: {
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingVertical: 6,
    paddingHorizontal: 15,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  terminalDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#4CAF50",
  },
  terminalTitle: {
    fontSize: 9,
    color: "rgba(255,255,255,0.6)",
    letterSpacing: 1,
  },
  timerBadgeTerminal: {
    marginLeft: "auto",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(0,0,0,0.2)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  timerBadgeTerminalLow: {
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    borderColor: "rgba(255, 107, 107, 0.2)",
    borderWidth: 1,
  },
  timerValueTerminal: {
    fontSize: 10,
    color: "rgba(255,255,255,0.6)",
    fontFamily: "monospace",
  },
  blurCard: {
    padding: 25,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    position: "relative",
    overflow: "hidden",
  },
  scanLine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
    zIndex: 10,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 20,
  },
  cardTitle: {
    fontSize: 10,
    letterSpacing: 2,
    color: "rgba(255,255,255,0.5)",
    fontWeight: "bold",
  },
  challengeBox: {
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    marginBottom: 25,
    height: 220,
    justifyContent: "center",
    position: "relative",
    overflow: "hidden",
  },
  challengeBoxHidden: {
    backgroundColor: "rgba(0,0,0,0.3)",
    borderStyle: "dashed",
    borderColor: "rgba(255,255,255,0.2)",
  },
  challengeBoxCompleted: {
    borderColor: "#4CAF50",
    backgroundColor: "rgba(76, 175, 80, 0.05)",
  },
  challengeBoxIncident: {
    borderColor: "#FF6B6B",
    borderStyle: "dashed",
    backgroundColor: "rgba(255, 107, 107, 0.05)",
  },
  hiddenContent: {
    alignItems: "center",
    justifyContent: "center",
    gap: 15,
  },
  lockIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "rgba(255,255,255,0.05)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  revealText: {
    fontSize: 14,
    color: "#FFF",
    letterSpacing: 2,
    fontWeight: "bold",
    textAlign: "center",
  },
  revealSubtext: {
    fontSize: 9,
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
    marginTop: 4,
    letterSpacing: 1,
  },
  challengeContent: {
    flex: 1,
    paddingVertical: 5,
    paddingHorizontal: 15,
  },
  quoteMarkTL: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 15,
    height: 15,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderColor: "rgba(255,255,255,0.2)",
  },
  quoteMarkBR: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 15,
    height: 15,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderColor: "rgba(255,255,255,0.2)",
  },
  challengeText: {
    fontSize: 20,
    lineHeight: 28,
    fontWeight: "700",
    color: "#FFF",
    textAlign: "center",
  },
  challengeTextCompleted: {
    color: "#4CAF50",
    opacity: 0.9,
  },
  errorSubtext: {
    fontSize: 10,
    color: "#FF6B6B",
    opacity: 0.8,
    fontStyle: "italic",
    marginTop: 15,
    textAlign: "center",
  },
  hideHint: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 10,
    opacity: 0.6,
  },
  hideHintText: {
    fontSize: 7,
    color: "rgba(255,255,255,0.3)",
    letterSpacing: 1,
    fontWeight: "bold",
  },
  tacticalCompleteBtn: {
    height: 60,
    backgroundColor: "rgba(76, 175, 80, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(76, 175, 80, 0.3)",
    borderRadius: 4,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
  },
  btnContentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  tacticalCompleteText: {
    fontSize: 14,
    color: "#4CAF50",
    letterSpacing: 2,
  },
  btnCornerTL: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 10,
    height: 10,
    borderTopWidth: 2,
    borderLeftWidth: 2,
    borderColor: "#4CAF50",
  },
  btnCornerBR: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 10,
    height: 10,
    borderBottomWidth: 2,
    borderRightWidth: 2,
    borderColor: "#4CAF50",
  },
  bluffBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 12,
    backgroundColor: "rgba(255, 217, 61, 0.05)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 217, 61, 0.2)",
    borderStyle: "dashed",
  },
  bluffBtnText: {
    fontSize: 9,
    color: "#FFD93D",
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  impossibleBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    backgroundColor: "rgba(255,107,107,0.05)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,107,107,0.2)",
    borderStyle: "dashed",
  },
  impossibleBtnText: {
    fontSize: 8.5,
    color: "rgba(255,107,107,0.6)",
    letterSpacing: 0.3,
    fontWeight: "bold",
  },
  pendingBadge: {
    marginTop: 20,
    backgroundColor: "rgba(255, 217, 61, 0.1)",
    padding: 15,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 217, 61, 0.3)",
    flexDirection: "row",
    alignItems: "center",
  },
  pendingBadgeText: {
    fontSize: 11,
    color: "#FFD93D",
    letterSpacing: 1,
    fontWeight: "bold",
  },
  pendingBadgeSub: {
    fontSize: 8,
    color: "rgba(255, 217, 61, 0.7)",
    marginTop: 2,
  },
  incidentStatus: {
    marginTop: 15,
    alignItems: "center",
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.05)",
  },
  incidentStatusText: {
    fontSize: 9,
    color: "rgba(255,255,255,0.4)",
    letterSpacing: 1,
  },
  cornerL_TL: {
    position: "absolute",
    top: 10,
    left: 10,
    width: 20,
    height: 20,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  cornerL_TR: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 20,
    height: 20,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  cornerL_BL: {
    position: "absolute",
    bottom: 10,
    left: 10,
    width: 20,
    height: 20,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  cornerL_BR: {
    position: "absolute",
    bottom: 10,
    right: 10,
    width: 20,
    height: 20,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
});
