import { StyleSheet } from 'react-native';
import { Theme } from '../constants/Theme';

export const styles = StyleSheet.create({
  sectionContainer: {
    borderWidth: 1,
    borderColor: Theme.colors.border,
    backgroundColor: Theme.colors.background,
    borderRadius: 8,
    overflow: "hidden",
  },
  agentsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: Theme.colors.surface,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.05)",
  },
  sectionTitle: {
    fontFamily: Theme.fonts.subtitle,
    fontSize: 10,
    color: "rgba(255, 255, 255, 0.5)",
    letterSpacing: 1,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  mapButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  mapButtonText: {
    fontFamily: Theme.fonts.subtitle,
    fontSize: 10,
    color: Theme.colors.red,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  agentsList: {
    backgroundColor: "transparent",
  },
  agentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.05)",
    backgroundColor: "transparent",
  },
  agentInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  agentTextContainer: {
    flexDirection: "column",
    justifyContent: "center",
  },
  agentName: {
    fontSize: 13,
    color: "#FFFFFF",
    fontWeight: "bold",
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  agentMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 1,
    gap: 12,
  },
  agentScore: {
    fontSize: 11,
    color: "rgba(255, 255, 255, 0.4)",
    fontWeight: "bold",
    lineHeight: 12,
  },
  statusWrapper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  statusText: {
    fontSize: 9,
    color: Theme.colors.status.online,
    fontWeight: "bold",
    letterSpacing: 0.5,
    lineHeight: 12,
  },
  statusDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: Theme.colors.status.online,
  },
  unmaskBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(139, 30, 30, 0.6)",
    backgroundColor: "rgba(139, 30, 30, 0.05)",
    gap: 6,
  },
  unmaskText: {
    fontSize: 9,
    color: Theme.colors.red,
    fontWeight: "bold",
    letterSpacing: 1,
    textShadowColor: "rgba(139, 30, 30, 0.4)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
});
