import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  incidentBanner: {
    backgroundColor: "rgba(255, 107, 107, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(255, 107, 107, 0.3)",
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  incidentBannerHost: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  incidentBannerSubject: {
    backgroundColor: "rgba(0,0,0,0.5)",
    borderColor: "rgba(255,107,107,0.2)",
  },
  majorityBadge: {
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
    marginHorizontal: 10,
    opacity: 0.4,
  },
  majorityBadgeActive: {
    backgroundColor: "rgba(76, 175, 80, 0.15)",
    opacity: 1,
  },
  majorityBadgeText: {
    fontSize: 7,
    color: "#FFF",
    fontWeight: "bold",
  },
  voterTally: {
    marginLeft: "auto",
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  voterTallyText: {
    fontSize: 7,
    color: "rgba(255,255,255,0.5)",
    fontWeight: "bold",
  },
  hostVerdictSection: {
    marginTop: 5,
  },
  voteBreakdown: {
    flexDirection: "row",
    gap: 15,
    marginBottom: 15,
  },
  voteColumn: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.2)",
    padding: 10,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "transparent",
  },
  voteColumnWinning: {
    borderColor: "rgba(255,255,255,0.15)",
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  columnTitle: {
    fontSize: 8,
    fontWeight: "bold",
    marginBottom: 6,
  },
  voterName: {
    fontSize: 10,
    color: "rgba(255,255,255,0.6)",
    marginBottom: 2,
  },
  voterNameEmpty: {
    fontSize: 9,
    color: "rgba(255,255,255,0.15)",
    fontStyle: "italic",
  },
  applyMajorityBtn: {
    backgroundColor: "#4CAF50",
    padding: 12,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 15,
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  applyMajorityText: {
    fontSize: 12,
    color: "#FFF",
    fontWeight: "900",
    letterSpacing: 1,
  },
  applyMajoritySub: {
    fontSize: 10,
    color: "rgba(255,255,255,0.8)",
  },
  tieText: {
    fontSize: 9,
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
    fontStyle: "italic",
    marginBottom: 15,
  },
  actionDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    marginBottom: 15,
  },
  hostDirectActions: {
    flexDirection: "row",
    gap: 10,
  },
  finalBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  finalBtnRecommended: {
    borderColor: "#FFF",
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  finalBtnText: {
    fontSize: 10,
    fontWeight: "bold",
  },
  subjectWaitBox: {
    alignItems: "center",
    paddingVertical: 15,
    backgroundColor: "rgba(0,0,0,0.2)",
    borderRadius: 8,
  },
  loadingDots: {
    flexDirection: "row",
    gap: 6,
    marginBottom: 12,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#FF6B6B",
  },
  incidentTitle: {
    fontSize: 10,
    color: "#FF6B6B",
    fontWeight: "700",
    letterSpacing: 2,
  },
  incidentHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  incidentText: {
    fontSize: 11,
    color: "#FFF",
    opacity: 0.8,
    lineHeight: 16,
    marginBottom: 10,
  },
  reportedChallengeBox: {
    backgroundColor: "rgba(0,0,0,0.3)",
    padding: 12,
    borderRadius: 6,
    borderLeftWidth: 2,
    borderLeftColor: "#FF6B6B",
    marginBottom: 15,
  },
  reportedChallengeText: {
    fontSize: 13,
    color: "#FFF",
    fontStyle: "italic",
    fontWeight: "600",
  },
  voteInstruction: {
    fontSize: 9,
    color: "rgba(255,255,255,0.4)",
    textAlign: "center",
    marginBottom: 10,
    letterSpacing: 1,
    fontWeight: "bold",
  },
  voteColumnSelected: {
    borderColor: "#4CAF50",
    backgroundColor: "rgba(76, 175, 80, 0.05)",
    borderWidth: 1.5,
  },
  universalVoteSection: {
    marginTop: 10,
  },
  breakdownDivider: {
    width: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    height: "80%",
    alignSelf: "center",
  },
  subjectActionsSection: {
    marginTop: 15,
    alignItems: "center",
  },
  subjectWaitBoxCompact: {
    paddingVertical: 10,
    opacity: 0.5,
  },
  hostFinalControl: {
    marginTop: 15,
  },
  hostActionBtn: {
    backgroundColor: "rgba(76, 175, 80, 0.15)",
    paddingVertical: 12,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "rgba(76, 175, 80, 0.3)",
  },
  hostActionBtnText: {
    fontSize: 11,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  voteActions: {
    flexDirection: "row",
    gap: 10,
  },
  voteBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 8,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  voteBtnSelectedImpossible: {
    backgroundColor: "#FF6B6B",
    borderColor: "#FF6B6B",
  },
  voteBtnSelectedFeasible: {
    backgroundColor: "#4CAF50",
    borderColor: "#4CAF50",
  },
  voteBtnText: {
    fontSize: 8,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "bold",
    letterSpacing: 1,
  },
});
